name: PowerShell Module CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Pester Tests
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
          Invoke-Pester -Path .\tests -Output Detailed

  package:
    name: Package PowerShell Module
    runs-on: windows-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Package Module
        shell: pwsh
        run: |
          $ModulePath = "$env:GITHUB_WORKSPACE\GameLibAutoArchiver"
          $Manifest = "$ModulePath\GameLibAutoArchiver.psd1"
          Compress-Archive -Path $ModulePath\* -DestinationPath "$ModulePath.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GameLibAutoArchiver
          path: GameLibAutoArchiver.zip